### ISSUE TITLE
Add annotation for the filename of the file that contains the value of the secret

### ISSUE THREAD

**Issue by jicowan** [aws-samples/aws-secret-sidecar-injector#14]
Create an annotation that allows the user to choose the name of the file to read from to get the value of the secret pulled from AWS Secrets Manager.  Update the init container to use that filename instead of defaulting to "secret" or use "secret" as the filename only when the annotation is absent.

**Comment by DimaNevelev** [comment]
Any ideas on how this should work in case of multiple secrets? (after merging #29)

**Comment by bo0tzz** [comment]
It looks like this is included in #29. @jicowan is there any indication on when those changes will be available in master?

**Comment by jicowan** [comment]
This was add in the last PR that was merged.
