### ISSUE TITLE
[Question] - When secret in the Secrets Manager rotate does pod needs to be restarted 

### ISSUE THREAD

**Issue by haofeif** [aws-samples/aws-secret-sidecar-injector#17]
Hi @jicowan 

Just would like to ask if the secret manager rotates its secret, does the pod have to be restarted ?
As it is an "init-container" may not be able to reflect the changes on the flight ?

**Comment by jicowan** [comment]
@haofeif we're in the process of building the rotation piece.  There should be another issue asking for feedback about the different approaches we've considered.  At present, you have to re-deploy the container each time the secret rotates.
