### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by antonosmond** [aws-samples/aws-secret-sidecar-injector#24]
Hi

I installed this with helm on an EKS cluster (1.16) and when I spin up a pod with the annotation to get the sidecar injected, they don't get the sidecar. 

In the secret-inject logs I see the following errors:
```
secret-inject-6bb9fb7bc4-8mmq8 secret-inject-init 2020/08/03 17:23:50 http: TLS handshake error from 10.10.201.141:36620: remote error: tls: bad certificate
secret-inject-6bb9fb7bc4-k76p9 secret-inject-init 2020/08/03 17:23:55 http: TLS handshake error from 10.10.201.141:38418: remote error: tls: bad certificate
secret-inject-6bb9fb7bc4-qs989 secret-inject-init 2020/08/03 17:24:07 http: TLS handshake error from 10.10.201.141:56584: remote error: tls: bad certificate
```

I'm sure I'm missing something simple here but any help would be greatly appreciated!

Thanks!

**Comment by antonosmond** [comment]
Just found it it's due to not being deployed in the `default` namespace and this will be fixed by https://github.com/aws-samples/aws-secret-sidecar-injector/pull/21

**Comment by amit0701** [comment]
Just pushed a new patch to the helm chart. The admission controller can now be installed in a custom namespace
