### ISSUE TITLE
Trust.json

### ISSUE THREAD

**Issue by murali2904** [aws-samples/aws-secret-sidecar-injector#27]
I am doing something wrong for creating trust.json . 

Could you please give some guidance. I am using default namespace.

$ read -r -d 'default' TRUST_RELATIONSHIP < trust.json
bash: trust.json: No such file or directory

**Comment by Mahendrasiddappa** [comment]
The blog post is missing the trust.json content. Try the following commands  - 
``` 
read -r -d '' TRUST_RELATIONSHIP <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "${OIDC_PROVIDER}:sub": "system:serviceaccount:default:webserver-service-account",
          "${OIDC_PROVIDER}:aud": "sts.amazonaws.com"
        }
      }
    }
  ]
}
EOF
```
```
echo "${TRUST_RELATIONSHIP}" > trust.json
```

**Comment by murali2904** [comment]
> echo "${TRUST_RELATIONSHIP}" > trust.json

Thanks for providing the information. It was sorted out.

>         command: ['sh', '-c', 'echo $(cat /tmp/secret) && sleep 3600']
> EOF
cat: /tmp/secret: No such file or directory
deployment.apps/webserver created

user@DESKTOP-QPBTQA6 MINGW64 ~
$ kubectl logs webserver-f4b6d5677-jwg4j


user@DESKTOP-QPBTQA6 MINGW64 ~
$


Pod was created successfully and pod is in running state. Not able to see password but i think it should work this way in real time scenario.

Thanks
Murali

**Comment by jicowan** [comment]
We will be updating the blog in the next few days.  Thanks for bringing this to our attention.
