### ISSUE TITLE
Feature request - inject secrets as env vars

### ISSUE THREAD

**Issue by antonosmond** [aws-samples/aws-secret-sidecar-injector#28]
It'd be really useful to have the ability to inject secrets as env vars as an alternative to mounting them in a file.
I'm fully aware that using env vars for secrets is a terrible security practice and leaves secrets exposed and people should NOT do this. However the reality is that sometimes we have to deal with things written by other people - helm charts, legacy applications etc and in some cases these expect the secrets to be set as env vars and provide no alternative way to configure them.

I'm currently dealing with a bunch of applications written in a variety of different languages that all expect their secrets in environment variables. This means my options are:
1. modify the code for all the applications to read each value from the file when needed
2. modify the code for all the applications to read the file at application startup and set the values as env vars
3. modify the Dockerfile (and/or entrypoint script) for all the applications  to read the file and set the env vars before starting the application

Options 1 & 2 won't be possible if I don't own or have access to the code and if can change the code, the solution would need to be different depending on the language of the app.
Option 3 is a little better as could be the same solution in all apps regardless of the app language however still involves updating the Dockerfiles etc for every app.

If secret-inject could set secrets as env vars it could work in all cases even when using other people stuff e.g. public helm charts.

If this is something you'd consider as a feature I'd be happy to attempt a PR to implement this functionality.

**Comment by amitkarpe** [comment]
@antonosmond ,
You might have to look into [ writeOutput](https://github.com/aws-samples/aws-secret-sidecar-injector/blob/ea339510ce614c2e3dbe34c72bf0e0c0a897a032/cmd/aws-secrets-manager/main.go#L78) function in [main.go ](https://github.com/aws-samples/aws-secret-sidecar-injector/blob/master/cmd/aws-secrets-manager/main.go#L78).


```
func writeOutput(output string) {
	f, err := os.Create("/tmp/secret")
	if err != nil {
		return
	}
	defer f.Close()

	f.WriteString(output)
}
```

Where based on some flag, we can either write into file (i.e. "/tmp/secrets") or convert this json file into evn var. To convert from json structure to env var, we can give try to [viper](github.com/spf13/viper).

**Comment by jicowan** [comment]
Yes, the GoDaddy project does this.
