### ISSUE TITLE
[Question] Deploying secret-inject  Controller in another namespace

### ISSUE THREAD

**Issue by sanketgawade** [aws-samples/aws-secret-sidecar-injector#32]
I am able to get all the workflow for secrets working within default namespace. 

Keeping the secret-inject controller in defailt namespace , when I try to deploy the controller into another namespace , i get errors. 

Error: rendered manifests contain a resource that already exists. Unable to continue with install: MutatingWebhookConfiguration "aws-secret-inject" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "chef-ns": current value is "default"

Can I deploy the controllers in multiple namespace within same eks cluster ?
How can i access secrets within multiple namespaces ?

**Comment by jicowan** [comment]
The solution is designed to work across namespaces.  In other words, you do not have to install the admission controller into multiple namespaces.

**Comment by sanketgawade** [comment]
I guess i found the issue in my deployment config volume , i am mounting.  Will close this issue , I wil reopen if needed  

Thanks for the help @jicowan

**Comment by jicowan** [comment]
No problem.  Glad you figured it out.
