### ISSUE TITLE
change secret mount point inside the container

### ISSUE THREAD

**Issue by dsaydon90** [aws-samples/aws-secret-sidecar-injector#38]
as mentioned in the `README.md`
> The Kubernetes dynamic admission controller also creates corresponding mountPath /tmp/secret for containers within the pod to access the secret

in my case, my app needs to use a secret file in a specific path in the file system which is not configurable.
There is any way to change the mount path from /tmp/secret to a configurable path?

currently, it seems that it's hard coded
https://github.com/aws-samples/aws-secret-sidecar-injector/blob/42faec484b137916a7bc9fac3759a6ba0a285433/cmd/aws-secrets-manager/main.go#L79

**Comment by nagasitaramthigulla** [comment]
It should be possible to use the dynamic location of the secret file.

**Comment by jicowan** [comment]
Created feature branch `secret_path` to work on this.

**Comment by jicowan** [comment]
@amit0701 can you update the injector with annotations that allow the user to specify the path and filename of the secret? I updated the sidecar in the branch `secret_path`.

**Comment by jicowan** [comment]
@dsaydon90 I believe we're nearly done with the testing. @amit0701 are you planning to merge your changes this week?

**Comment by jicowan** [comment]
https://github.com/aws-samples/aws-secret-sidecar-injector/pull/44
