### ISSUE TITLE
Feature Request - AWS Parameter Store Integration

### ISSUE THREAD

**Issue by ibrahiem96** [aws-samples/aws-secret-sidecar-injector#42]
We are looking for a solution that can also work with AWS Parameter Store. Is this a feature you guys can add, and if its not something you're planning on looking into in the short-term, I'd be happy with some direction as to what can be modified so we can use this with AWS Param Store

Thanks

**Comment by jicowan** [comment]
@ibrahiem96 we weren't planning to build an integration with parameter store, but you could use a similar pattern, i.e. use an init container and mount as a volume. Did you want to reference them as ENVs?

**Comment by ibrahiem96** [comment]
@jicowan Yes I was planning to reference them as ENVs. Could you point me to some files or the part of your codebase that pertains to the init container -- so I can use it as an example?

**Comment by jicowan** [comment]
It's in [main.go](https://github.com/aws-samples/aws-secret-sidecar-injector/blob/master/cmd/aws-secrets-manager/main.go).  We are not mapping secrets to ENVs.  We're mounting them as volumes.
