### ISSUE TITLE
Init container isn't started for webserver + TLS handshake error in secret-inject

### ISSUE THREAD

**Issue by kagarlickij** [aws-samples/aws-secret-sidecar-injector#43]
Hi there! 
I'm following instructions but getting only `webserver` container in my `webserver-78578795c6-6l2mx` pod
No init container is present there

In my `secret-inject-87fd4b8bb-v6jvp` pod logs I see `http: TLS handshake error from 192.168.183.197:43904: remote error: tls: bad certificate` exception on each webserver deploy attempt 
 
Any ideas how to debug / fix it?

**Comment by amit0701** [comment]
Hello,

That can typically occur when there is a cert mismatch between the admission controller and the mutating webhook configuration. I doubt if certs have expired (since they are valid for 3650 days). Is this a new clean-state deployment ? Verify that you dont have an existing secret named "secret-inject-tls" which was created as a part of previous Helm deployment.

**Comment by kagarlickij** [comment]
I've just completed full k8s redeploy and still getting exactly the same.
Worse mentioning that other sample deploy that is using IAM OIDC, role and policy to reach S3 via Amazon EKS Pod Identity Webhook works just fine. 

I have k8s v1.19, nodePool v1.19.6-20210302, CNI v1.7.9-eksbuild.1 if it matters

**Comment by shashankbansal6** [comment]
I have the same issue. 

```                                                                                                                    
2021/03/11 00:13:02 http: TLS handshake error from ********: remote error: tls: bad certificate
2021/03/11 00:13:02 http: TLS handshake error from ********: remote error: tls: bad certificate
```
K8s details:
```
kubectl version --short                                                                                                                                                                
Client Version: v1.19.3
Server Version: v1.19.6-eks-49a6c0
```

**Comment by jicowan** [comment]
@shashankbansal6 and @kagarlickij we're testing this against 1.19 now.  Perhaps something changed in that release.

**Comment by themattkeating** [comment]
I'm now also having this issue after upgrading to 1.19

**Comment by jicowan** [comment]
I believe we need to add a SAN to the certificate.

**Comment by amit0701** [comment]
@kagarlickij @shashankbansal6 This should be fixed.

**Comment by themattkeating** [comment]
@amit0701 Please can you confirm where you added the SAN? I dont see any commits to the repo and I'm using the multi-secret branch.

**Comment by jicowan** [comment]
We're not actively maintaining that branch @themattkeating. You could ask @dnascimento if he has plans to update the certificate.

**Comment by themattkeating** [comment]
Unfortunately the master branch only supports a single secret, which is almost useless in the real world. 

@jicowan If you could explain which certificate was updated, Im happy to do a PR for this multi-secret branch. I just wanted to know more about what the fix was.

**Comment by jicowan** [comment]
The changes are in the gh-pages branch: 
https://github.com/aws-samples/aws-secret-sidecar-injector/commits/gh-pages
